version: 2
updates:

  # Maintain Dockerfile dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: daily
      time: "08:00"
      timezone: "Europe/London"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates every week
      interval: "weekly"
    # Update multiple dependencies at the same time
    groups:
      github-actions:
        patterns:
          - "*"

  # Maintain pip dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      # Check for updates every week
      interval: "weekly"
    # Update multiple dependencies at the same time
    groups:
      pip:
        patterns:
          - "*"
