coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5
    patch:
      default:
        target: 75
ignore:
  - "test/"
  - "ldap_jwt_auth/routers/*" # ignore routers as they are not unit tested
