services:
  ldap-jwt-auth:
    container_name: ldap-jwt-auth
    build:
      context: .
      target: dev
    volumes:
      - ./ldap_jwt_auth:/app/ldap_jwt_auth
      - ./keys:/app/keys
      - ./ldap_server_certs/cacert.pem:/app/ldap_server_certs/cacert.pem
      - ./users_config.yaml:/app/users_config.yaml
      - ./maintenance/maintenance.json:/app/maintenance/maintenance.json
      - ./maintenance/scheduled_maintenance.json:/app/maintenance/scheduled_maintenance.json
      - ./logging.ini:/app/logging.ini
    env_file:
      - path: ./.env
    ports:
      - 8000:8000
    restart: on-failure
