FROM python:3.12.7-alpine3.20@sha256:e75de178bc15e72f3f16bf75a6b484e33d39a456f03fc771a2b3abb9146b75f8

WORKDIR /ldap-jwt-auth-run

COPY README.md pyproject.toml ./
# Copy ldap_jwt_auth source files
COPY ldap_jwt_auth/ ldap_jwt_auth/

RUN set -eux; \
    \
    # Install python-ldap system dependencies \
    apk add --no-cache build-base openldap-dev python3-dev; \
    \
    # Install pip dependencies \
    python -m pip install --no-cache-dir .; \
    \
    # Create loging.ini from its .example file \
    cp ldap_jwt_auth/logging.example.ini ldap_jwt_auth/logging.ini; \
    \
    # Create a non-root user to run as \
    addgroup -g 500 -S ldap-jwt-auth; \
    adduser -S -D -G ldap-jwt-auth -H -u 500 -h /ldap-jwt-auth-run ldap-jwt-auth;

USER ldap-jwt-auth

CMD ["uvicorn", "ldap_jwt_auth.main:app", "--app-dir", "/ldap-jwt-auth-run", "--host", "0.0.0.0", "--port", "8000"]
EXPOSE 8000
