services:
  ldap-jwt-auth:
    container_name: ldap-jwt-auth
    build:
      context: .
      target: dev
    volumes:
      - ./ldap_jwt_auth:/app/ldap_jwt_auth
      - ./keys:/app/keys
      - ./ldap_server_certs/cacert.pem:/app/ldap_server_certs/cacert.pem
      - ./users_config.yaml:/app/users_config.yaml
      - ./maintenance/maintenance.json:/app/maintenance/maintenance.json
      - ./maintenance/scheduled_maintenance.json:/app/maintenance/scheduled_maintenance.json
      - ./logging.ini:/app/logging.ini
    env_file:
      - path: ./.env
    ports:
      - 8004:8000
    restart: on-failure
    depends_on:
      - keycloak
    extra_hosts:
      # Want to use localhost for keycloak connection so the presigned URLs are correct but also want to avoid using
      # host networking
      - "localhost:host-gateway"

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    command: start-dev --import-realm
    volumes:
      - ./keycloak/testrealm.json:/opt/keycloak/data/import/testrealm.json
    restart: always
    ports:
      - 9004:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: dev-file
