services:
  ldap-jwt-auth:
    container_name: ldap-jwt-auth
    build:
      context: .
      target: dev
    volumes:
      - ./ldap_jwt_auth:/app/ldap_jwt_auth
      - ./keys:/app/keys
      - ./ldap_server_certs/cacert.pem:/app/ldap_server_certs/cacert.pem
      - ./active_usernames.txt:/app/active_usernames.txt
      - ./maintenance/maintenance.json:/app/maintenance/maintenance.json
      - ./maintenance/scheduled_maintenance.json:/app/maintenance/scheduled_maintenance.json
      - ./logging.ini:/app/logging.ini
    env_file:
      - path: ./.env
    ports:
      - 8000:8000
    restart: on-failure
    depends_on:
      - keycloak
    network_mode: "host"
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    command: start-dev --import-realm
    volumes:
      - ./keycloak/testrealm.json:/opt/keycloak/data/import/testrealm.json
    restart: always
    ports:
      - 9001:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: dev-file
