roles:
  admin:
    userIsAdmin: true
  moderator:
    userIsAdmin: false

users:
  - username: abc123
    email: abc123@example.com
    roles: [admin, moderator]

  - username: def456
    roles: [moderator]

  - email: ghi789@example.com
    roles: []
