roles:
  admin:
    userIsAdmin: true
  site-admin:
    userIsAdmin: false

users:
  - username: abc123
    email: test@example.com
    role: admin

  - username: def456
    role: site-admin

  - email: ghi789@example.com
