roles:
  admin:
    userIsAdmin: true
  moderator:
    userIsAdmin: false

users:
  - username: abc123
    email: abc123@example.com
    role: admin

  - username: def456
    role: moderator

  - email: ghi789@example.com
